import { toBigInt } from '../utils.ts';

export const USD_PER_MATERIAL = 40;
export const USD_PER_LABOR = 4_000;

export function usdToMaterial(usd: number): bigint {
  return toBigInt(usd / USD_PER_MATERIAL);
}

export const GPU_POWER_MW_PER_UNIT = 0.002;
export const SOLAR_PANEL_POWER_MW = 0.0006;
export const SOLAR_OUTPUT_MULTIPLIER_EARTH = 1.0;
export const SOLAR_OUTPUT_MULTIPLIER_MOON = 1.35;
export const SOLAR_OUTPUT_MULTIPLIER_MERCURY = 3.2;
export const SOLAR_OUTPUT_MULTIPLIER_SPACE_SSO = 3.8;
export const SOLAR_FARM_PANELS = 1_000_000;
export const TARGET_EARTH_SOLAR_POWER_TW = 3;
export const TARGET_EARTH_SOLAR_POWER_MW = TARGET_EARTH_SOLAR_POWER_TW * 1_000_000;
export const MAX_EARTH_SOLAR_PANELS = Math.round(
  TARGET_EARTH_SOLAR_POWER_MW / (SOLAR_PANEL_POWER_MW * SOLAR_OUTPUT_MULTIPLIER_EARTH),
);
export const SOLAR_FARM_LIMIT = Math.round(MAX_EARTH_SOLAR_PANELS / SOLAR_FARM_PANELS);
export const MEGA_DATACENTER_GPU_CAPACITY = 1_000_000;
export const MEGA_DATACENTER_LIMIT = Math.round(
  TARGET_EARTH_SOLAR_POWER_MW / (GPU_POWER_MW_PER_UNIT * MEGA_DATACENTER_GPU_CAPACITY),
);
export const MOON_GPU_DATACENTER_GPUS_PER_BUILD = 1_000_000;
export const MOON_MAX_SOLAR_POWER_MW = MAX_EARTH_SOLAR_PANELS * SOLAR_PANEL_POWER_MW * SOLAR_OUTPUT_MULTIPLIER_MOON;
export const MOON_GPU_DATACENTER_LIMIT = Math.round(
  MOON_MAX_SOLAR_POWER_MW / (GPU_POWER_MW_PER_UNIT * MOON_GPU_DATACENTER_GPUS_PER_BUILD),
);
export const API_USER_SYNTH_BASE_RATE = 1000n;
export const ROCKET_LOSS_NO_REUSE = 1.0;
export const GPU_SATELLITE_FACTORY_OUTPUT_PER_MONTH = 6;
export const GPU_SATELLITE_GPU_REQ_PER_MONTH = 300;
export const GPU_SATELLITE_SOLAR_PANEL_REQ_PER_MONTH = Math.round(
  (GPU_SATELLITE_GPU_REQ_PER_MONTH * GPU_POWER_MW_PER_UNIT) / (SOLAR_PANEL_POWER_MW * SOLAR_OUTPUT_MULTIPLIER_SPACE_SSO),
);
export const DYSON_SWARM_FACILITY_OUTPUT_PER_MONTH = GPU_SATELLITE_FACTORY_OUTPUT_PER_MONTH;
export const DYSON_SWARM_FACILITY_MATERIAL_REQ_PER_MONTH = 2_000;
export const DYSON_SWARM_FACILITY_LABOR_REQ_PER_MONTH = 200;
export const VON_NEUMANN_PROBE_OUTPUT_PER_MONTH = 12;
export const VON_NEUMANN_PROBE_MATERIAL_REQ_PER_MONTH = 100_000;
export const VON_NEUMANN_PROBE_LABOR_REQ_PER_MONTH = 5_000;
export const RESEARCH_COST_MULTIPLIER = 10_000n;
