import { scaleBigInt, toBigInt } from '../utils.ts';
import type { ResearchConfig } from './Types.ts';

export const RESEARCH_CONFIGS: ResearchConfig[] = [
  {
    id: 'algoEfficiency1',
    name: 'Algorithmic Efficiency +30%',
    cost: toBigInt(1),
    costResource: 'code',
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.3,
    quantityLabel: 'Training Speed',
    quantityBase: 1,
    quantityEmoji: 'flops',
    quantityUnit: 'x',
    prereqs: [],
    description: 'Improvements to training algorithms speed up training.',
    effect: { type: 'algoEfficiency' },
  },
  {
    id: 'apiAutoPricing',
    name: 'API Auto Pricing',
    cost: toBigInt(0.1),
    costResource: 'code',
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock automatic API price adjustments',
  },
  {
    id: 'computeAutoAllocation',
    name: 'Compute Auto Allocation',
    cost: toBigInt(2),
    costResource: 'code',
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['apiAutoPricing'],
    description: 'Unlock automatic compute allocation',
  },
  {
    id: 'synthData2',
    name: 'API Data Generation (+100%)',
    cost: toBigInt(1000),
    costResource: 'code',
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'API User Data Rate',
    quantityBase: 1000,
    quantityEmoji: 'data',
    quantityUnit: '/m',
    prereqs: [],
    description: 'API user data generation scales infinitely.',
    effect: { type: 'apiUserSynthRate' },
  },
  {
    id: 'syntheticData1',
    name: 'Synthetic Data',
    cost: toBigInt(20000),
    costResource: 'code',
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock AI Data Synthesizer job',
  },
  {
    id: 'syntheticData2',
    name: 'Synthetic Data Output (+100%)',
    cost: toBigInt(6_000_000),
    costResource: 'code',
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Synthesizer Output',
    quantityBase: 10,
    quantityEmoji: 'data',
    quantityUnit: '/m',
    prereqs: ['syntheticData1'],
    description: 'AI Data Synthesizer output scales infinitely.',
    effect: { type: 'jobProduction', jobs: ['aiDataSynthesizer'] },
  },
  {
    id: 'solarTechnology',
    name: 'Solar Manufacturing',
    cost: toBigInt(0.1),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock mining, solar factories, and solar farms',
  },
  {
    id: 'chipManufacturing',
    name: 'Chip Manufacturing',
    cost: toBigInt(2_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock Earth GPU factories',
  },
  {
    id: 'robotics1',
    name: 'Robotics',
    cost: toBigInt(10_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 0.5,
    prereqs: ['solarTechnology'],
    description: 'Unlock robot workers.',
    effect: { type: 'jobProduction', jobs: ['robotWorker'] },
  },
  {
    id: 'robotFactoryEngineering1',
    name: 'Robot Factory Engineering I',
    cost: toBigInt(80_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['robotics1'],
    description: 'Unlock Earth robot factories',
  },
  {
    id: 'rocketry',
    name: 'Rocketry',
    cost: toBigInt(10_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['solarTechnology', 'chipManufacturing'],
    description: 'Unlock Earth rocket and GPU satellite factories plus orbital deployment UI',
  },
  {
    id: 'payloadToMoon',
    name: 'Lunar Transport',
    cost: toBigInt(5_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['rocketry'],
    description: 'Unlock Earth->Moon logistics and Moon installation UI',
  },
  {
    id: 'moonMineEngineering',
    name: 'Moon Mining & Solar',
    cost: toBigInt(20_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMoon'],
    description: 'Unlock Moon material mines and solar factories',
  },
  {
    id: 'moonChipManufacturing',
    name: 'Moon GPU Manufacturing',
    cost: toBigInt(20_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['moonMineEngineering'],
    description: 'Unlock Moon GPU factories',
  },
  {
    id: 'moonMassDrivers',
    name: 'Moon Mass Drivers',
    cost: toBigInt(100_000_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['moonChipManufacturing'],
    description: 'Unlock Moon GPU satellite factories and mass drivers (more launches, larger payload)',
  },
  {
    id: 'moonRobotics',
    name: 'Moon Robotics',
    cost: toBigInt(20_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMoon', 'robotFactoryEngineering1'],
    description: 'Unlock Moon robot factories',
  },
  {
    id: 'payloadToMercury',
    name: 'Mercury Transport',
    cost: toBigInt(1_500_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMoon', 'moonMassDrivers'],
    description: 'Unlock Moon->Mercury logistics and all Mercury buildings',
  },
  {
    id: 'mercuryRobotics',
    name: 'Mercury Robotics',
    cost: toBigInt(1_000_000),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMercury', 'moonRobotics'],
    description: 'Unlock Mercury robot factories',
  },
  {
    id: 'reusableRockets1',
    name: 'Rocket Reusability (+100%)',
    cost: toBigInt(100_000),
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 0.5,
    quantityLabel: 'Rocket Loss',
    quantityBase: 100,
    quantityEmoji: 'rockets',
    quantityUnit: '%',
    prereqs: ['rocketry'],
    description: 'Rocket losses scale down infinitely.',
    effect: { type: 'rocketLoss' },
  },
  {
    id: 'robotics2',
    name: 'Robot Labor Output (+100%)',
    cost: toBigInt(100_000),
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Robot Labor Output',
    quantityBase: 0.5,
    quantityEmoji: 'labor',
    quantityUnit: '/m',
    prereqs: ['robotics1'],
    description: 'Robot labor output scales infinitely.',
    effect: { type: 'jobProduction', jobs: ['robotWorker'] },
  },
  {
    id: 'facilityThroughput1',
    name: 'Facility Throughput (+100%)',
    cost: toBigInt(80_000_000),
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Facility Output',
    quantityBase: 1,
    quantityEmoji: 'flops',
    quantityUnit: 'x',
    prereqs: ['payloadToMercury'],
    description: 'All industrial facilities scale infinitely.',
    effect: {
      type: 'facilityProduction',
      facilities: [
        'materialMine',
        'solarFactory',
        'robotFactory',
        'gpuFactory',
        'rocketFactory',
        'gpuSatelliteFactory',
        'dysonSwarmFacility',
      ],
    },
  },
  {
    id: 'jobThroughput1',
    name: 'Workforce Throughput (+50%)',
    cost: toBigInt(900_000_000),
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.5,
    quantityLabel: 'AI Job Output',
    quantityBase: 1,
    quantityEmoji: 'code',
    quantityUnit: 'x',
    prereqs: ['payloadToMercury'],
    description: 'All AI job output scales infinitely.',
    effect: {
      type: 'jobProduction',
      jobs: ['aiSWE', 'aiResearcher', 'aiDataSynthesizer', 'manager'],
    },
  },
  {
    id: 'vonNeumannProbes',
    name: 'Von Neumann Probes',
    cost: scaleBigInt(1_000_000_000_000n),
    minLevel: 1,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMercury', 'robotics2'],
    description: 'Unlock endgame probe launch',
  },
  {
    id: 'gpuArch1',
    name: 'GPU Architecture (+50%)',
    cost: toBigInt(4_000),
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.5,
    quantityLabel: 'GPU FLOPS',
    quantityBase: 1,
    quantityEmoji: 'flops',
    quantityUnit: 'x',
    prereqs: ['chipManufacturing'],
    description: 'GPU performance scales infinitely.',
    effect: { type: 'gpuFlops' },
  },
];
