import type { ResearchConfig, ResearchCostResource } from './Types.ts';

export const RESEARCH_PRICE_EXPONENT_BY_RESOURCE: Record<ResearchCostResource, number> = {
  code: 1.5,
  science: 1.5,
};

export const RESEARCH_CONFIGS: ResearchConfig[] = [
  {
    id: 'algoEfficiency1',
    name: 'Algorithmic Efficiency',
    costResource: 'code',
    minLevel: 24,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.1,
    quantityLabel: 'Training Speed',
    quantityBase: 1,
    quantityEmoji: 'flops',
    quantityUnit: 'x',
    prereqs: [],
    description: 'Improvements to training algorithms speed up training.',
    effect: { type: 'algoEfficiency' },
  },
  {
    id: 'agentMultiplexing1',
    name: 'Agent Multiplexing',
    costResource: 'code',
    minLevel: 35,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Agents per GPU',
    quantityBase: 32,
    quantityUnit: 'agents/GPU',
    prereqs: [],
    description: 'Increase agents supported per GPU.',
    effect: { type: 'agentsPerGpu' },
  },
  {
    id: 'apiAutoPricing',
    name: 'API Auto Pricing',
    costResource: 'code',
    minLevel: 18,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock automatic API price adjustments',
  },
  {
    id: 'computeAutoAllocation',
    name: 'Compute Auto Allocation',
    costResource: 'code',
    minLevel: 25,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['apiAutoPricing'],
    description: 'Unlock automatic compute allocation',
  },
  {
    id: 'synthData2',
    name: 'API Data Generation',
    costResource: 'code',
    minLevel: 41,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'API User Data Rate',
    quantityBase: 1000,
    quantityEmoji: 'data',
    quantityUnit: '/m',
    prereqs: [],
    description: 'API user data generation scales infinitely.',
    effect: { type: 'apiUserSynthRate' },
  },
  {
    id: 'syntheticData1',
    name: 'Synthetic Data',
    costResource: 'code',
    minLevel: 48,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock AI Data Synthesizer job',
  },
  {
    id: 'syntheticData2',
    name: 'Synthetic Data Output',
    costResource: 'code',
    minLevel: 62,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Synthesizer Output',
    quantityBase: 10,
    quantityEmoji: 'data',
    quantityUnit: '/m',
    prereqs: ['syntheticData1'],
    description: 'AI Data Synthesizer output scales infinitely.',
    effect: { type: 'jobProduction', jobs: ['aiDataSynthesizer'] },
  },
  {
    id: 'solarTechnology',
    name: 'Solar Manufacturing',
    minLevel: 18,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock mining, solar factories, and solar farms',
  },
  {
    id: 'chipManufacturing',
    name: 'Chip Manufacturing',
    minLevel: 42,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: [],
    description: 'Unlock Earth GPU factories',
  },
  {
    id: 'researchProductivity1',
    name: 'Research Productivity',
    costResource: 'code',
    minLevel: 24,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.5,
    quantityLabel: 'Research Output',
    quantityBase: 1,
    quantityEmoji: 'science',
    quantityUnit: 'x',
    prereqs: [],
    description: 'Human and AI researchers produce more science.',
    effect: { type: 'jobProduction', jobs: ['humanResearcher', 'aiResearcher'] },
  },
  {
    id: 'codeProductivity1',
    name: 'Code Productivity',
    costResource: 'science',
    minLevel: 1,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.5,
    quantityLabel: 'Code Output',
    quantityBase: 1,
    quantityEmoji: 'code',
    quantityUnit: 'x',
    prereqs: [],
    description: 'Human and AI coders produce more code.',
    effect: { type: 'jobProduction', jobs: ['humanSWE', 'aiSWE'] },
  },
  {
    id: 'robotics1',
    name: 'Robotics',
    minLevel: 46,
    isInfinite: false,
    quantityMultiplierPerLevel: 0.5,
    prereqs: ['solarTechnology'],
    description: 'Unlock robot workers.',
    effect: { type: 'jobProduction', jobs: ['robotWorker'] },
  },
  {
    id: 'robotFactoryEngineering1',
    name: 'Robot Factory Engineering I',
    minLevel: 52,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['robotics1'],
    description: 'Unlock Earth robot factories',
  },
  {
    id: 'rocketry',
    name: 'Rocketry',
    minLevel: 46,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['solarTechnology', 'chipManufacturing'],
    description: 'Unlock Earth rocket and GPU satellite factories plus orbital deployment UI',
  },
  {
    id: 'payloadToMoon',
    name: 'Lunar Transport',
    minLevel: 62,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['rocketry'],
    description: 'Unlock Earth->Moon logistics and Moon installation UI',
  },
  {
    id: 'moonMineEngineering',
    name: 'Moon Mining & Solar',
    minLevel: 65,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMoon'],
    description: 'Unlock Moon material mines and solar factories',
  },
  {
    id: 'moonChipManufacturing',
    name: 'Moon GPU Manufacturing',
    minLevel: 65,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['moonMineEngineering'],
    description: 'Unlock Moon GPU factories',
  },
  {
    id: 'moonMassDrivers',
    name: 'Moon Mass Drivers',
    minLevel: 86,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['moonChipManufacturing'],
    description: 'Unlock Moon GPU satellite factories and mass drivers (more launches, larger payload)',
  },
  {
    id: 'moonRobotics',
    name: 'Moon Robotics',
    minLevel: 65,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMoon', 'robotFactoryEngineering1'],
    description: 'Unlock Moon robot factories',
  },
  {
    id: 'payloadToMercury',
    name: 'Mercury Transport',
    minLevel: 76,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMoon', 'moonMassDrivers'],
    description: 'Unlock Moon->Mercury logistics and all Mercury buildings',
  },
  {
    id: 'mercuryRobotics',
    name: 'Mercury Robotics',
    minLevel: 58,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMercury', 'moonRobotics'],
    description: 'Unlock Mercury robot factories',
  },
  {
    id: 'reusableRockets1',
    name: 'Rocket Reusability',
    minLevel: 52,
    isInfinite: true,
    quantityMultiplierPerLevel: 0.5,
    quantityLabel: 'Rocket Loss',
    quantityBase: 100,
    quantityEmoji: 'rockets',
    quantityUnit: '%',
    prereqs: ['rocketry'],
    description: 'Rocket losses scale down infinitely.',
    effect: { type: 'rocketLoss' },
  },
  {
    id: 'robotics2',
    name: 'Robot Labor Output',
    minLevel: 52,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Robot Labor Output',
    quantityBase: 0.5,
    quantityEmoji: 'labor',
    quantityUnit: '/m',
    prereqs: ['robotics1'],
    description: 'Robot labor output scales infinitely.',
    effect: { type: 'jobProduction', jobs: ['robotWorker'] },
  },
  {
    id: 'facilityThroughput1',
    name: 'Facility Throughput',
    minLevel: 69,
    isInfinite: true,
    quantityMultiplierPerLevel: 2,
    quantityLabel: 'Facility Output',
    quantityBase: 1,
    quantityEmoji: 'flops',
    quantityUnit: 'x',
    prereqs: ['payloadToMercury'],
    description: 'All industrial facilities scale infinitely.',
    effect: {
      type: 'facilityProduction',
      facilities: [
        'materialMine',
        'solarFactory',
        'robotFactory',
        'gpuFactory',
        'rocketFactory',
        'gpuSatelliteFactory',
        'dysonSwarmFacility',
      ],
    },
  },
  {
    id: 'jobThroughput1',
    name: 'Workforce Throughput',
    minLevel: 75,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.5,
    quantityLabel: 'AI Job Output',
    quantityBase: 1,
    quantityEmoji: 'code',
    quantityUnit: 'x',
    prereqs: ['payloadToMercury'],
    description: 'All AI job output scales infinitely.',
    effect: {
      type: 'jobProduction',
      jobs: ['aiSWE', 'aiResearcher', 'aiDataSynthesizer', 'manager'],
    },
  },
  {
    id: 'vonNeumannProbes',
    name: 'Von Neumann Probes',
    minLevel: 92,
    isInfinite: false,
    quantityMultiplierPerLevel: 1,
    prereqs: ['payloadToMercury', 'robotics2'],
    description: 'Unlock endgame probe launch',
  },
  {
    id: 'gpuArch1',
    name: 'GPU Architecture',
    minLevel: 44,
    isInfinite: true,
    quantityMultiplierPerLevel: 1.5,
    quantityLabel: 'GPU FLOPS',
    quantityBase: 1,
    quantityEmoji: 'flops',
    quantityUnit: 'x',
    prereqs: ['chipManufacturing'],
    description: 'GPU performance scales infinitely.',
    effect: { type: 'gpuFlops' },
  },
];
