export interface HintEntry {
  title: string;
  bodyHtml: string;
}

export const HINTS = {
  'resource.funds': {
    title: 'Funds',
    bodyHtml: `
      <p>Main currency. Most purchases, salaries, and upgrades consume funds.</p>
      <p>Real-world inspiration: cloud/software businesses convert model capability into recurring revenue streams.</p>
      <p class="hint-sources">Example source: <a href="https://www.microsoft.com/en-us/investor/earnings/fy-2025-q1/press-release-webcast" target="_blank" rel="noopener noreferrer">Microsoft FY2025 Q1 earnings (cloud/AI demand)</a>.</p>
    `,
  },
  'resource.intel': {
    title: 'Intel',
    bodyHtml: `
      <p>Effective model capability. Higher intel unlocks new jobs/research and increases AI job speed.</p>
      <p>See also: <span class="hint-inline-link hint-target" data-hint-id="resource.flops">FLOPS</span>, <span class="hint-inline-link hint-target" data-hint-id="resource.data">Data</span>.</p>
      <p class="hint-sources">Example source: <a href="https://www.anthropic.com/news/the-anthropic-economic-index" target="_blank" rel="noopener noreferrer">Anthropic Economic Index</a>.</p>
    `,
  },
  'resource.flops': {
    title: 'FLOPS',
    bodyHtml: `
      <p>Compute throughput available for agents, inference, and training.</p>
      <p>In game and in reality, large models are bounded by both compute and <span class="hint-inline-link hint-target" data-hint-id="resource.energy">energy</span>.</p>
      <p class="hint-sources">Source: <a href="https://www.iea.org/reports/electricity-2025/executive-summary" target="_blank" rel="noopener noreferrer">IEA Electricity 2025 (data centers and electricity demand)</a>.</p>
    `,
  },
  'resource.code': {
    title: 'Code',
    bodyHtml: `
      <p>Engineering output used for research, API optimization, and progression gates.</p>
      <p>Generated by both human and AI coder jobs.</p>
      <p class="hint-sources">Labor market baseline: <a href="https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm" target="_blank" rel="noopener noreferrer">U.S. BLS Software Developers</a>.</p>
    `,
  },
  'resource.science': {
    title: 'Science',
    bodyHtml: `
      <p>Research output needed for advanced technologies and model progression.</p>
      <p>Generated by researcher jobs and spent on research unlocks.</p>
      <p class="hint-sources">Labor market baseline: <a href="https://www.bls.gov/ooh/life-physical-and-social-science/computer-and-information-research-scientists.htm" target="_blank" rel="noopener noreferrer">U.S. BLS Computer & Information Research Scientists</a>.</p>
    `,
  },
  'resource.labor': {
    title: 'Labor',
    bodyHtml: `
      <p>Person-month style construction/operations capacity for physical infrastructure.</p>
      <p>Used to build and run industrial/supply facilities.</p>
      <p class="hint-sources">Labor market baseline: <a href="https://www.bls.gov/ooh/construction-and-extraction/construction-laborers-and-helpers.htm" target="_blank" rel="noopener noreferrer">U.S. BLS Construction Laborers and Helpers</a>.</p>
    `,
  },
  'resource.energy': {
    title: 'Energy',
    bodyHtml: `
      <p>Power supply must meet demand. If demand exceeds supply, systems throttle.</p>
      <p>See also: <span class="hint-inline-link hint-target" data-hint-id="infra.gasPlant">Gas Plants</span>, <span class="hint-inline-link hint-target" data-hint-id="infra.nuclearPlant">Nuclear Plants</span>, <span class="hint-inline-link hint-target" data-hint-id="mechanic.gridPower">Grid Power</span>.</p>
      <p class="hint-sources">Sources: <a href="https://www.iea.org/reports/electricity-2025/executive-summary" target="_blank" rel="noopener noreferrer">IEA Electricity 2025</a>, <a href="https://news.constellationenergy.com/2024-09-20-Constellation-to-Restart-Crane-Clean-Energy-Center,-Launch-Major-New-Partnership-with-Microsoft" target="_blank" rel="noopener noreferrer">Constellation + Microsoft nuclear announcement (2024)</a>.</p>
    `,
  },
  'resource.data': {
    title: 'Data',
    bodyHtml: `
      <p>Training corpus and synthetic data inputs. Needed to train higher capability models.</p>
      <p>Generated through synthesis and market purchases.</p>
      <p class="hint-sources">Example source: <a href="https://epoch.ai/data-insights" target="_blank" rel="noopener noreferrer">Epoch AI data availability analysis</a>.</p>
    `,
  },
  'resource.gpus': {
    title: 'GPUs',
    bodyHtml: `
      <p>Primary accelerator resource. GPUs produce <span class="hint-inline-link hint-target" data-hint-id="resource.flops">FLOPS</span> but consume <span class="hint-inline-link hint-target" data-hint-id="resource.energy">energy</span>.</p>
      <p>In this game, one GPU unit represents a card plus fractional host hardware.</p>
      <p class="hint-sources">Example source: <a href="https://www.nvidia.com/en-us/data-center/h100/" target="_blank" rel="noopener noreferrer">NVIDIA H100 data center GPU specs</a>.</p>
    `,
  },
  'resource.nudge': {
    title: 'Nudges',
    bodyHtml: `
      <p>Management interventions used to clear <span class="hint-inline-link hint-target" data-hint-id="mechanic.stuck">stuck agents</span>.</p>
      <p>Produced by Agent Manager jobs and spent automatically each tick when available.</p>
    `,
  },
  'resource.material': {
    title: 'Material',
    bodyHtml: `
      <p>Ore-equivalent mass input for factories and heavy infrastructure.</p>
      <p>Represents blended raw + refined material requirements in simplified form.</p>
    `,
  },
  'resource.solarPanels': {
    title: 'Solar Panels',
    bodyHtml: `
      <p>Physical panels used to generate power (Earth/Moon) and support orbital systems.</p>
      <p class="hint-sources">Example module baseline: <a href="https://www.longi.com/en/products/modules/" target="_blank" rel="noopener noreferrer">LONGi utility-scale module specs</a>.</p>
    `,
  },
  'resource.robots': {
    title: 'Robots',
    bodyHtml: `
      <p>Industrial workers for off-world and automated labor pipelines.</p>
      <p>Robots are logistics-constrained by launches and route capacity.</p>
    `,
  },
  'resource.rockets': {
    title: 'Rockets',
    bodyHtml: `
      <p>Transport capacity for moving payloads between Earth, Moon, Mercury, and orbit.</p>
      <p>Rockets are reusable with losses based on reuse technology level.</p>
      <p class="hint-sources">Example source: <a href="https://www.spacex.com/updates/#starship-update" target="_blank" rel="noopener noreferrer">SpaceX Starship updates (reusability focus)</a>.</p>
    `,
  },
  'resource.gpuSatellites': {
    title: 'GPU Satellites',
    bodyHtml: `
      <p>Orbital compute/power infrastructure used in the late-game logistics loop.</p>
      <p>They consume panel/GPU/rocket supply-chain capacity before paying off in sustained output.</p>
    `,
  },
  'mechanic.jobs': {
    title: 'Jobs',
    bodyHtml: `
      <p>Assign agents/workers to jobs to transform one bottleneck into another.</p>
      <p>Jobs are your main pacing lever in early/mid game.</p>
    `,
  },
  'mechanic.agentCapacity': {
    title: 'Agent Capacity',
    bodyHtml: `
      <p>Agent activity is limited by available compute. In early game this is CPU cores; in GPU era it is compute allocation.</p>
      <p>Unassigned agents do nothing until moved to active jobs.</p>
    `,
  },
  'mechanic.stuck': {
    title: 'Stuck Agents',
    bodyHtml: `
      <p>Active AI agents can become stuck over time. Stuck agents stop producing until nudged.</p>
      <p>See also: <span class="hint-inline-link hint-target" data-hint-id="mechanic.nudge">Nudges</span>.</p>
    `,
  },
  'mechanic.nudge': {
    title: 'Nudges and Managers',
    bodyHtml: `
      <p>Manager output becomes nudge budget that automatically clears stuck agents.</p>
      <p>The system smooths random stuck spikes with a small carry buffer.</p>
      <p>See also: <span class="hint-inline-link hint-target" data-hint-id="resource.nudge">Nudge Resource</span>, <span class="hint-inline-link hint-target" data-hint-id="mechanic.stuck">Stuck Agents</span>.</p>
    `,
  },
  'mechanic.datacenters': {
    title: 'Datacenters',
    bodyHtml: `
      <p>Datacenters cap how many Earth GPUs can be installed and active.</p>
      <p>Building shells and MEP infrastructure are modeled separately from GPU purchases.</p>
      <p class="hint-sources">Industry pattern: hyperscale operators often stage shell/power buildout independently from IT hardware deployment.</p>
    `,
  },
  'mechanic.gridPower': {
    title: 'Grid Power',
    bodyHtml: `
      <p>Buy or sell grid capacity in kW to close short-term supply/demand gaps.</p>
      <p>Useful as a bridge while you build long-lead generation assets.</p>
    `,
  },
  'mechanic.spaceLogistics': {
    title: 'Space Logistics',
    bodyHtml: `
      <p>Routes have transit time, return time, and payload limits. Overcommitting one route starves others.</p>
      <p>Late game is primarily logistics-constrained, not just production-constrained.</p>
    `,
  },
  'mechanic.apiServices': {
    title: 'API Services',
    bodyHtml: `
      <p>API demand responds to awareness, model intelligence, and price.</p>
      <p>Code spending optimizes inference efficiency, lowering PFLOPS per user and increasing effective capacity.</p>
      <p>This creates a market loop where pricing, optimization, and compute allocation all matter.</p>
    `,
  },
  'research.algoEfficiency': {
    title: 'Algo Efficiency',
    bodyHtml: `
      <p>These upgrades model algorithmic progress as a direct training-speed multiplier.</p>
      <p>In this balance pass, each tier gives 3x faster training.</p>
      <p class="hint-sources">Reference: <a href="https://epoch.ai/gradient-updates/how-has-ai-progressed-so-fast" target="_blank" rel="noopener noreferrer">Epoch AI on algorithmic efficiency trends (about 3x/year)</a>.</p>
    `,
  },
  'infra.micMini': {
    title: 'Muck-mini PC',
    bodyHtml: `
      <p>Early-game hardware expansion that adds CPU cores to support more active agents.</p>
      <p>Acts as a temporary bridge before full GPU era transition.</p>
    `,
  },
  'infra.gasPlant': {
    title: 'Gas Plants',
    bodyHtml: `
      <p>Faster-to-deploy dispatchable generation with lower capex than nuclear in this balance model.</p>
      <p class="hint-sources">Reference: <a href="https://www.eia.gov/outlooks/aeo/" target="_blank" rel="noopener noreferrer">U.S. EIA AEO cost assumptions</a>.</p>
    `,
  },
  'infra.nuclearPlant': {
    title: 'Nuclear Plants',
    bodyHtml: `
      <p>High-capacity, high-capex baseload option for sustained datacenter growth.</p>
      <p>Real-world AI/datacenter operators are again evaluating nuclear partnerships.</p>
      <p class="hint-sources">Example: <a href="https://news.constellationenergy.com/2024-09-20-Constellation-to-Restart-Crane-Clean-Energy-Center,-Launch-Major-New-Partnership-with-Microsoft" target="_blank" rel="noopener noreferrer">Constellation + Microsoft (2024)</a>.</p>
    `,
  },
  'infra.solarInstall': {
    title: 'Solar Installation',
    bodyHtml: `
      <p>Converts stockpiled panels into installed capacity. Installation rate is labor-constrained.</p>
      <p class="hint-sources">Reference: <a href="https://www.energy.gov/eere/solar/solar-energy-technologies-office" target="_blank" rel="noopener noreferrer">U.S. DOE Solar Energy Technologies Office</a>.</p>
    `,
  },
  'infra.gpuFactory': {
    title: 'GPU Factory',
    bodyHtml: `
      <p>Represents a single-tool fab module (roughly one lithography machine with supporting line ops).</p>
      <p>Throughput/labor are tuned to order-of-magnitude semiconductor manufacturing constraints, not hand-assembly rates.</p>
      <p class="hint-sources">References: <a href="https://www.asml.com/en/products/duv-lithography-systems/twinscan-nxt1980fi" target="_blank" rel="noopener noreferrer">ASML NXT:1980i (DUV throughput)</a>, <a href="https://www.asml.com/en/products/euv-lithography-systems/twinscan-nxe-3800e" target="_blank" rel="noopener noreferrer">ASML NXE:3800E (EUV platform)</a>, <a href="https://investor.tsmc.com/english/annual-reports" target="_blank" rel="noopener noreferrer">TSMC annual reports (capacity and staffing context)</a>.</p>
    `,
  },
  'job.sixxerBasic': {
    title: 'Sixxer Basic',
    bodyHtml: `
      <p>Entry cashflow work. Low-barrier, low-margin contract tasks.</p>
      <p>Purpose: bootstrap funds before higher-value loops unlock.</p>
    `,
  },
  'job.sixxerEnterprise': {
    title: 'Sixxer Enterprise',
    bodyHtml: `
      <p>Higher-value service work with stronger payout and higher capability requirement.</p>
      <p>Represents moving upmarket from commodity gigs to enterprise contracts.</p>
    `,
  },
  'job.manager': {
    title: 'Agent Manager',
    bodyHtml: `
      <p>Produces <span class="hint-inline-link hint-target" data-hint-id="resource.nudge">nudges</span> to clear <span class="hint-inline-link hint-target" data-hint-id="mechanic.stuck">stuck agents</span>.</p>
      <p>Useful when AI headcount grows and stochastic stuck losses become material.</p>
    `,
  },
  'job.aiSWE': {
    title: 'AI Coder',
    bodyHtml: `
      <p>Converts compute + intelligence into code throughput.</p>
      <p>Primary technical production loop for software-side progression.</p>
    `,
  },
  'job.aiResearcher': {
    title: 'AI Researcher',
    bodyHtml: `
      <p>Generates science output for advanced research gates.</p>
      <p>Typically becomes bottlenecked by compute and power availability.</p>
    `,
  },
  'job.aiDataSynthesizer': {
    title: 'AI Data Synthesizer',
    bodyHtml: `
      <p>Produces synthetic data to relieve training-data bottlenecks.</p>
      <p>Intended to matter most when model requirements outpace affordable market data.</p>
    `,
  },
  'job.humanSWE': {
    title: 'Human Coder',
    bodyHtml: `
      <p>Human code throughput with recurring salary cost.</p>
      <p class="hint-sources">Labor baseline: <a href="https://www.bls.gov/ooh/computer-and-information-technology/software-developers.htm" target="_blank" rel="noopener noreferrer">U.S. BLS Software Developers</a>.</p>
    `,
  },
  'job.humanResearcher': {
    title: 'Human Researcher',
    bodyHtml: `
      <p>Human science throughput with salary drag.</p>
      <p class="hint-sources">Labor baseline: <a href="https://www.bls.gov/ooh/life-physical-and-social-science/computer-and-information-research-scientists.htm" target="_blank" rel="noopener noreferrer">U.S. BLS C&IR Scientists</a>.</p>
    `,
  },
  'job.humanWorker': {
    title: 'Human Worker',
    bodyHtml: `
      <p>General labor for construction/operations pipelines.</p>
      <p class="hint-sources">Labor baseline: <a href="https://www.bls.gov/ooh/construction-and-extraction/construction-laborers-and-helpers.htm" target="_blank" rel="noopener noreferrer">U.S. BLS Construction Laborers and Helpers</a>.</p>
    `,
  },
  'job.robotWorker': {
    title: 'Robot Worker',
    bodyHtml: `
      <p>Automated labor source with higher upfront cost but scalable operations.</p>
      <p>Critical for off-world expansion where human staffing is constrained.</p>
    `,
  },
} as const satisfies Record<string, HintEntry>;

export type HintId = keyof typeof HINTS;

export function getHint(hintId: string): HintEntry | null {
  return hintId in HINTS ? HINTS[hintId as HintId] : null;
}
